name: CI Football Predictor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Configuration de Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lancement de l'application Streamlit (test de démarrage)
      run: |
        # On crée un faux fichier secrets pour que l'app ne plante pas au démarrage
        mkdir -p .streamlit
        echo '[API_FOOTBALL_KEY]\n"dummy-key-for-ci"' > .streamlit/secrets.toml
        
        # On lance l'application en arrière-plan en mode "headless"
        streamlit run 1_Matchs_du_Jour.py --server.runOnSave=false --server.headless=true &
        
        # On attend quelques secondes pour voir si le serveur plante
        sleep 15
        
        # On vérifie si le processus Streamlit est toujours en cours
        if pgrep -f "streamlit run 1_Matchs_du_Jour.py"; then
          echo "L'application Streamlit a démarré avec succès."
          # On arrête le serveur pour que le workflow puisse se terminer
          pkill -f "streamlit run"
        else
          echo "Erreur : L'application Streamlit n'a pas pu démarrer ou a planté."
          exit 1
        fi
