name: CI Football Predictor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Configuration de Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lancement de l'application (test de démarrage)
      run: |
        # On lance l'application en arrière-plan
        # On utilise une fausse clé API car les secrets ne sont pas disponibles pour les PR de forks
        export API_FOOTBALL_KEY="dummy-key-for-ci"
        ./run.sh &
        # On attend quelques secondes pour voir si le serveur plante
        sleep 10
        # On vérifie si le processus est toujours en cours
        # `ps -ef` liste les processus, `grep` filtre pour notre app, `grep -v grep` enlève le processus grep lui-même
        if pgrep -f "python app.py"; then
          echo "L'application a démarré avec succès."
          # On arrête le serveur pour que le workflow puisse se terminer
          pkill -f "python app.py"
        else
          echo "Erreur : L'application n'a pas pu démarrer ou a planté."
          exit 1
        fi
